services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
      - typesense
    ports:
      - 3000:3000

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
      UPLOAD_LIMIT: 300M
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  typesense:
    image: typesense/typesense:29.0
    restart: on-failure
    ports:
      - "8108:8108"
    command: '--data-dir /data --api-key=xyz'

volumes:
  mysql-data:
  typesense-data: